spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: recipes
  data:
    mongodb:
      database: recipes-api-db
      uri: ${MONGODB}
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    verify:
      host: ${VERIFY_EMAIL_HOST}
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true

        
